### PR TITLE
ditto-markov init commit

### PR DESCRIPTION
**Pull request by ridhoq**
Starting point for ditto-markov service

### CODE REVIEW

**Review by austinpray — APPROVED** [review]
LGTM

cant test this locally cause I don't have a cosmos db with the right schema 

Maybe in future PR you could add https://github.com/Azure/azure-cosmos-db-emulator-docker to docker-compose

**Comment by ridhoq** [comment]
So that's a Windows docker image 🙃 

https://github.com/zeit/cosmosdb-server is prolly the best we're gonna get

**Comment by ridhoq** [comment]
Literally, the Cosmos DB emulator instructions for OS X and Linux tell you to run a Windows VM: https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator#running-on-mac-or-linux. Based MS

**Comment by austinpray** [comment]
Linux and OSX bros did we get too cocky??

**Pull request merged**
